name: CI Pipeline

on:
  push:
    branches: [ "**" ]         # Kør ved push på alle branches
  pull_request:
    branches: [ "**" ]         # Kør også ved pull requests

jobs:
  build-and-test:
    runs-on: ubuntu-latest     # GitHub Actions kører på en Linux-maskine

    steps:
      # 1. Hent kildekoden
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Java 21 (Temurin JDK)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # 3. Byg projekt og kør tests (Spring Boot + H2)
      - name: Build and Test
        run: mvn -B -Dspring.profiles.active=test clean verify

      # 4. Upload testresultater (valgfrit, men nyttigt for CI)
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: |
            **/target/surefire-reports/*.xml
            **/target/failsafe-reports/*.xml
